# This file provides meta-data for https://github.com/BigWigsMods/packager

package-as: Questie

manual-changelog:
  filename: CHANGELOG.md
  markup-type: markdown

ignore:
  - .dockerfiles
  - .git
  - .github
  - .types
  - .vscode
  - cli
  - Database/TBC
  - ExternalScripts(DONOTINCLUDEINRELEASE)
  - Localization/lookups/TBC
  - releases
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .gitmodules
  - .luacheckrc
  - cli.lua
  - Questie-BCC.toc
  - "*.py"

embedded-libraries:
  - Ace-3.0
  - CallbackHandler-1.0
  - HereBeDragons
  - LibCompress
  - LibDataBroker-1.1
  - LibDBIcon-1.0
  - LibSharedMedaia-3.0
  - LibStub
  - LibUIDropDownMenu
